// Generated by scripts/write-config.js — public values only (anon key, guarded by RLS).
window.SUPABASE_URL = "https://fdkigbowuiehwmtagwlt.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZka2lnYm93dWllaHdtdGFnd2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0MzY2MDAsImV4cCI6MjEwNzAxMjYwMH0.KEi4XKYOZ1gbzb0mPwlMToUJth12k1C0x5M2QhvLbhc";
