#!/usr/bin/env node
/*
 * Writes js/supabase-config.js from .env so the public pages can reach
 * Supabase.
 *
 *   node scripts/write-config.js
 *
 * Only the project URL and the anon key go into the page. The anon key is
 * meant to be public — RLS (supabase/migrations/0002, 0003) is what limits
 * it. The service role key must never end up in this file; the check below
 * refuses one.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const env = Object.fromEntries(
  fs.readFileSync(path.join(ROOT, '.env'), 'utf8')
    .split(/\r?\n/)
    .filter(l => /^\s*[A-Z_]+\s*=/.test(l))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);

const url = env.SUPABASE_URL, key = env.SUPABASE_ANON_KEY;
if (!url || !key) {
  console.error('SUPABASE_URL and SUPABASE_ANON_KEY must both be set in .env');
  process.exit(1);
}
if (key === env.SUPABASE_SERVICE_ROLE_KEY || key.startsWith('sb_secret_')) {
  console.error('SUPABASE_ANON_KEY looks like the service role key. Refusing to publish it.');
  process.exit(1);
}
// Legacy JWT keys carry their role in the payload; make sure it is anon.
if (key.startsWith('eyJ')) {
  try {
    const role = JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString()).role;
    if (role !== 'anon') { console.error(`SUPABASE_ANON_KEY has role "${role}", expected "anon". Refusing.`); process.exit(1); }
  } catch { /* not decodable — let Supabase reject it */ }
}

const out = path.join(ROOT, 'js', 'supabase-config.js');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `// Generated by scripts/write-config.js — public values only (anon key, guarded by RLS).
window.SUPABASE_URL = ${JSON.stringify(url)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`);
console.log('wrote js/supabase-config.js');
